Improve alternate-create-sftp-user with checks and ssh auth keys

diff --git a/files/alternate-create-sftp-user b/files/alternate-create-sftp-user
--- a/files/alternate-create-sftp-user
+++ b/files/alternate-create-sftp-user
@@ -10,8 +10,9 @@ rePass='[^:]{0,255}'
 reUid='[[:digit:]]*'
 reGid='[[:digit:]]*'
 reDir='[^:]*'
-reKey='ssh-[^,:]*'
+reKey='[^:]*'
 #reArgs="^($reUser)(:$rePass)(:e)?(:$reUid)?(:$reGid)?(:$reDir)?$"
+reAuthLine='^ssh-[[:alnum:]]{2,20} [[:alnum:]+/]{10,} .*$'
 
 function log() {
     echo "[$0] $*"
@@ -30,7 +31,7 @@ function validateArg() {
     fi
 }
 
-log "Parsing user data: \"$1\""
+log "Parsing user data (line from users.conf)"
 IFS=':' read -ra args <<< "$1"
 
 skipIndex=0
@@ -51,13 +52,15 @@ gid="${args[$((skipIndex+3))]}"; validateArg "GID" "$gid" "$reGid" || exit 1
 dir="${args[$((skipIndex+4))]}"; validateArg "dirs" "$dir" "$reDir" || exit 1
 key="${args[$((skipIndex+5))]}"; validateArg "keys" "$key" "$reKey" || exit 1
 
-passwd_entry=$( getent passwd "$user" )
+log "User $user: obtaining /etc/passwd entry"
 
-log "Parsing passwd entry: \"$passwd_entry\""
+passwd_entry="$( getent passwd "$user" || true)"
+
 IFS=':' read -ra pwentry <<< "$passwd_entry"
 
-if [-n "$passwd_entry" ] ; then
+if [ -n "$passwd_entry" ] ; then
     already_exists=1
+    Log "User $user already exists (might use usermod)"
 fi
 
 if [ -n "$uid" ]; then
@@ -78,7 +81,9 @@ if [ -n "$gid" ]; then
 fi
 
 if [ "$already_exists" ] ; then
-  usermod "${usermodOptions[@]}" "$user"
+  if [ "${usermodOptions[#]}" -ne 0 ] ; then
+    usermod "${usermodOptions[@]}" "$user"
+  fi
 else
   useradd "${useraddOptions[@]}" "$user"
 fi
@@ -96,11 +101,12 @@ mkdir -p "/home/$user/.ssh"
 chown -R "$uid:root" "/home/$user/.ssh"
 chmod 700 "/home/$user/.ssh"
 
-log "Changing password"
-
+# Is simpler to change password every time than work out if it has changed
 if [ -n "$pass" ]; then
+    log "Changing password"
     echo "$user:$pass" | chpasswd $chpasswdOptions
 else
+    log "Disabling password"
     usermod -p "*" "$user" # disabled password
 fi
 
@@ -136,34 +142,38 @@ if [ -d "$userKeysQueuedDir" ]; then
         done
     fi
 fi
+log "Number of keys found: $( cat $userKeysAllowedFileTmp | wc -l )"
 
-log "Reading authorized keys from user file"
+log "Reading authorized keys from users.conf"
 
 if [ -n "$key" ] ; then
-    IFS=',' read -ra keyArgs <<< "$dir"
+    IFS=',' read -ra keyArgs <<< "$key"
     for keyStr in "${keyArgs[@]}"; do
         echo "${keyStr}" >> "$userKeysAllowedFileTmp"
     done
 fi
 
+log "Number of keys found: $( cat $userKeysAllowedFileTmp | wc -l )"
+
 #  If tmp file exist and has any content
 if [ -s "$userKeysAllowedFileTmp" ] ; then
-    # Sort
-    # Remove duplicate keys
-    # Filter only valid authorized_keys entries
+    log "Filtering duplicated or invalid keys"
     sort < "$userKeysAllowedFileTmp" |
       uniq |
-      grep -E "^ssh-[:alnum:]{3-20} [/+[:alnum:]]{10,255} .*$" 
-      > "$userKeysAllowedFileTmp2"
+      grep -E "$reAuthLine" > "$userKeysAllowedFileTmp2" || true #ignore error in empty result
+
+    log "Total number of keys found: $( cat $userKeysAllowedFileTmp2 | wc -l )"
 
     if diff -q "$userKeysAllowedFileTmp2" "$userKeysAllowedFile" > /dev/null 2>&1 ; then
       log "No changes in auhtorized_keys detected"
     else
+      log "Creating final '$userKeysAllowedFile' file"
       mv "$userKeysAllowedFileTmp2" "$userKeysAllowedFile"
     fi
 fi
 
 if [ -f "$userKeysAllowedFile" ] ; then
+    log "Setting strict permissions on '$userKeysAllowedFile' file"
     chown "$uid" "$userKeysAllowedFile"
     chmod 600 "$userKeysAllowedFile"
 fi
